errores = {
        "sram_controller": ["Error en SRAM Controller"],
        "internal_sram": ["Error en Internal SRAM (16KB)"],
        "clipper": ["Error en Clipper"],
        "Input_Data": ["Error en Input Data"],
        "formatter_in": ["Error en Formatter 64x32 FIFO Clipper"],
        "decoder": ["Fallo en el Decoder"],
        "scaler_rotator": ["Error en Scaler|Rotator"],
        "palette": ["Error en Palette"],
        "padding": ["Error en Padding"],
        "CLOCK_IN": ["Error en Clock In"],
        "pll": ["Error en PLL"],
        "System_Clock": ["System Clock desconfigurado"],
        "encoder": ["Error en Encoder"],
        "formatter_out": ["Error en Formatter 64x32 FIFO"],
        "Output_Data": ["Error en Output Data"],
        "Control_Data": ["Error en Control Data"],
        "command_port_interface": ["Error en Command Port Interface"],
    }
    
diagnostico = {
        "sram_controller": ["Diagnostico: Reiniciar Dispositivo"],
        "internal_sram": ["Diagnostico: Reiniciar Dispositivo"],
        "clipper": ["Diagnostico: Cambiar Clipper"],
        "Input_Data": ["Diagnostico: Revise bien la Conexion"],
        "formatter_in": ["Diagnostico: Cambie el Formatter"],
        "decoder": ["Diagnostico: Cambiar el Decoder"],
        "scaler_rotator": ["Diagnostico: Cambiar el Scalar Rotator"],
        "palette": ["Diagnostico: Cambiar el Palette"],
        "padding": ["Diagnostico: Cambiar el Padding"],
        "CLOCK_IN": ["Diagnostico: Reiniciar el Dispositivo"],
        "pll": ["Diagnostico: Reinicar el Discpositivo"],
        "System_Clock": ["Diagnostico: Reiniciar el Dispositivo"],
        "encoder": ["Diagnostico: Cambiar el Encoder"],
        "formatter_out": ["Diagnostico: Cambiar el Formatter"],
        "Output_Data": ["Diagnostico: Revisar la Conexion"],
        "Control_Data": ["Diagnostico: Reiniciar el Dispositivo"],
        "command_port_interface": ["Diagnostico: Revisar la Conexion"],
    }
    